# Generated by Django 5.1.2 on 2024-10-11 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itineraries", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("icon", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="itinerary",
            name="budget",
            field=models.CharField(
                choices=[
                    ("$", "Budget ($)"),
                    ("$$", "Standard ($$)"),
                    ("$$$", "Comfy ($$$)"),
                    ("$$$$", "Lux ($$$$)"),
                    ("$$$$$", "Premium ($$$$$)"),
                ],
                max_length=5,
            ),
        ),
        migrations.RemoveField(
            model_name="itinerary",
            name="preferred_activities",
        ),
        migrations.AddField(
            model_name="itinerary",
            name="preferred_activities",
            field=models.ManyToManyField(to="itineraries.activity"),
        ),
    ]
