# Generated by Django 5.1.2 on 2024-10-11 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itineraries", "0003_budget_alter_itinerary_budget"),
    ]

    operations = [
        migrations.RenameField(
            model_name="itinerary",
            old_name="travel_dates",
            new_name="start_date",
        ),
        migrations.RemoveField(
            model_name="itinerary",
            name="budget",
        ),
        migrations.AddField(
            model_name="itinerary",
            name="budget_levels",
            field=models.ManyToManyField(to="itineraries.budget"),
        ),
        migrations.AddField(
            model_name="itinerary",
            name="duration",
            field=models.IntegerField(
                choices=[
                    (1, "1 day"),
                    (3, "3 days"),
                    (5, "5 days"),
                    (7, "7 days"),
                    (14, "14 days"),
                ],
                default=3,
            ),
            preserve_default=False,
        ),
    ]
